### PR TITLE
Created base method to create or add to judgments

### PR DESCRIPTION
**Pull request by mbracks**
# [CPF-3349](https://trippinc.atlassian.net/browse/CPF-3349)
- [x] Updated Version
- [x] Updated Change Log

# Description
- Added a method to the base Judicator class to help with adding to or creating new judgments.
- Updated MaterialJudicator to reference this new method.

# Testing
Please create a checklist of what to test for.
- [x] No compile errors in Unity Editor
- [x] Material Judicator still reports infractions

[CPF-3349]: https://trippinc.atlassian.net/browse/CPF-3349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Gabo-7** [comment]
Tried running Lex on Phoenix model: 

imagen

**Comment by Gabo-7** [comment]
imagen

**Review by Gabo-7 — CHANGES_REQUESTED** [review]
imagen

Please update the version and changelog

**Review by TrungVNguyen — COMMENTED** [review]
I didn't have any error when I pass judgment on a material. There is one note is that CreateOrAddInfractionsToJudgment has multiple nested if statements that can be simplified. 
`protected Judgment CreateOrAddInfractionsToJudgment(List<Infraction> infractions, Judgment judgment, Object accused)
{
    if (infractions == null)
    {
        Debug.LogError($"Judicator : {this}\nNull infractions list provided when attempting to create a new judgment.");
        return judgment;
    }

    if (judgment == null)
    {
        if (accused == null)
        {
            Debug.LogError($"Judicator : {this}\nNull accused object provided when attempting to create a new judgment.");
            return null;
        }

        judgment = new Judgment
        {
            accused = accused,
            infractions = new List<Infraction>()
        };
    }

    judgment.infractions ??= new List<Infraction>();
    judgment.infractions.AddRange(infractions);

    return judgment;
}
`

**Review by TrungVNguyen — APPROVED** [review]

**Comment by mbracks** [comment]
Simplified the initialization logic, updated the version number, and the change log.

**Review by Gabo-7 — APPROVED** [review]

**Pull request merged**
